services:
  - type: web
    name: ambos-backend
    env: dotnet
    rootDir: backend
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/ProyectoAmbos_Alanski.dll --urls=http://0.0.0.0:$PORT
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: ambos-mysql
          property: connectionString
      - key: JWT_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: http://localhost:4200

databases:
  - name: ambos-mysql
    databaseName: ambos_db
    user: ambos_user